### ISSUE TITLE
Generate events with Vertica datasource

### ISSUE THREAD

**Issue by edsonbittencourt** [rajsameer/vertica-datasource#6]
Hello dev, thanks for your amazing work. I'm already using the plugin.

I have a question about the progress of the project. Here we need to collect the data of Vertica database and generate events, but I know that at this moment this option is disabled.

Do you intend to enable this feature in future releases, making possible generate alerts? I hope so.

Thank you again for your plugin. It already helps me a lot.

**Comment by rajsameer** [comment]
Hello @iambittenco,
Thanks for first issue on this repo, and thank you for the feedback it means a lot.
Right now there are few things going on , I was contacted by the Vertica team, and they have announced their data source plugin [](https://github.com/vertica/vertica-grafana-datasource ). You could use this plugin and see if alerting works out for you.
I am going to gradually integrate my features in Vertica plugin too.    
Regarding the alerting features , yes I wanted to enable them in future releases.  But I will first port my changes to Vertica plugin and if the alerting works fine there I will deprecate this plugin.

I believe right now the Vertica plugin is not yet published, but will be soon its in progress.

**Comment by edsonbittencourt** [comment]
> Hello @iambittenco,
> 
> Thanks for first issue on this repo, and thank you for the feedback it means a lot.
> 
> Right now there are few things going on , I was contacted by the Vertica team, and they have announced their data source plugin [](https://github.com/vertica/vertica-grafana-datasource ). You could use this plugin and see if alerting works out for you.
> 
> I am going to gradually integrate my features in Vertica plugin too.    
> 
> Regarding the alerting features , yes I wanted to enable them in future releases.  But I will first port my changes to Vertica plugin and if the alerting works fine there I will deprecate this plugin.
> 
> 
> 
> I believe right now the Vertica plugin is not yet published, but will be soon its in progress.

Thank you so much for the quickly answer.
